# GitHub Secret Scanning Allowlist
# Firebase API keys are public client-side keys and safe to expose
# These are false positives from GitHub's secret scanning

paths-allowlist:
  # Firebase client-side config files
  - 'config/config.js'
  - 'config/firebase-config.js'
  - 'dist/config.js'
  - 'dist/firebase-config.js'
  - 'scripts/config.js'
  - 'scripts/firebase-config.js'
  # HTML files that may contain Firebase config
  - '**/*.html'
